language: node_js

node_js:
  - "6"

sudo: false

cache:
  directories:
    - node_modules

script:
  - "npm test"

branches:
  only:
    - master
    - /^greenkeeper/.*$/
  except:
    - /^v\d+\.\d+\.\d+$/

notifications:
  email:
    - honza@hommer.cz
